version: "3.9"

services:
  tgbot:
    image: minter.tgbot:latest
    container_name: minter.tgbot
    restart: unless-stopped
    env_file:
      - ".env"
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - minter.postgres.network

  postgres:
    container_name: minter.postgres
    image: "postgres:15-alpine"
    hostname: minter.postgres
    restart: unless-stopped
    expose:
      - "5432"
    # ports:
    #   - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    networks:
      - minter.postgres.network
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: ${POSTGRES_USER:-$USER}
      POSTGRES_DB: ${POSTGRES_DB:-$USER}
    volumes:
      - minter.postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  minter.postgres.data: {}

networks:
  minter.postgres.network: {}